// Code generated by mockery v2.9.4. DO NOT EDIT.

package frameio

import (
	signal "github.com/jamescostian/signal-to-sms/utils/proto/signal"
	mock "github.com/stretchr/testify/mock"
)

// MockFrameWriter is an autogenerated mock type for the FrameWriter type
type MockFrameWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: backupFrame, blob
func (_m *MockFrameWriter) Write(backupFrame *signal.BackupFrame, blob []byte) error {
	ret := _m.Called(backupFrame, blob)

	var r0 error
	if rf, ok := ret.Get(0).(func(*signal.BackupFrame, []byte) error); ok {
		r0 = rf(backupFrame, blob)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
