name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Cross-compilation support
        run: |
          # First, set things up for Apple. OSXCross will be used, which needs libssl1.0-dev
          mkdir ../../osxcross
          git clone https://github.com/plentico/osxcross-target.git ../../osxcross/target
          echo 'deb http://security.ubuntu.com/ubuntu bionic-security main' | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt-cache policy libssl1.0-dev
          # Finally, install libssl1.0-dev, plus MinGW for Windows
          sudo apt install libssl1.0-dev gcc-multilib gcc-mingw-w64
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HOMEBREW_GITHUB_TOKEN: ${{secrets.HOMEBREW_ACCESS_TOKEN}}
